package Pantallas;

//imports
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
//---
import javax.swing.JOptionPane;

//Minor
public class Empleados extends javax.swing.JFrame {
    //metodo conectar base de datos---------------------------------

    public static Connection getConnection() {
        Connection con = null;
        try {
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost"
                    + ":3306/super_compre_barato", "root", "joseminor");
            JOptionPane.showMessageDialog(null, "Conexion exitosa");

        } catch (Exception e) {
            System.out.println(e);
        }
        return con;
    }
    //---------------------------------------------------------------------
    //metodo limpiar los espacios de los textos

    public void limpiarTxt() {
        jTextFieldCEDULA.setText(null);
        jTextFieldNOMBRE.setText(null);
        jTextFieldAPELLIDO_1.setText(null);
        jTextFieldAPELLIDO_2.setText(null);
        jTextFieldEDAD.setText(null);
        jTextFieldRESIDENCIA.setText(null);
        jTextFieldPUESTO.setText(null);
        jTextFieldCONTRASENIA.setText(null);
        jTextField_ID.setText(null);

    }
    //------------------------------------------

   
    public Empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCEDULA = new javax.swing.JTextField();
        jTextFieldNOMBRE = new javax.swing.JTextField();
        jTextFieldAPELLIDO_1 = new javax.swing.JTextField();
        jTextFieldAPELLIDO_2 = new javax.swing.JTextField();
        jTextFieldEDAD = new javax.swing.JTextField();
        jTextFieldRESIDENCIA = new javax.swing.JTextField();
        jTextFieldPUESTO = new javax.swing.JTextField();
        jTextFieldCONTRASENIA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ButtonAGREGAR = new javax.swing.JButton();
        ButtonMODIFICAR = new javax.swing.JButton();
        jButtonBUSCAR = new javax.swing.JButton();
        jButtonELIMINAR = new javax.swing.JButton();
        ButtonLIMPIAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido1:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido2:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Residencia:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Puesto");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña:");

        jTextFieldCEDULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCEDULAActionPerformed(evt);
            }
        });

        jTextFieldEDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEDADActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id:");

        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Empleados");

        ButtonAGREGAR.setText("Agregar");
        ButtonAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAGREGARActionPerformed(evt);
            }
        });

        ButtonMODIFICAR.setText("Modificar");
        ButtonMODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMODIFICARActionPerformed(evt);
            }
        });

        jButtonBUSCAR.setText("Buscar");
        jButtonBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBUSCARActionPerformed(evt);
            }
        });

        jButtonELIMINAR.setText("Eliminar");
        jButtonELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonELIMINARActionPerformed(evt);
            }
        });

        ButtonLIMPIAR.setText("LIMPIAR");
        ButtonLIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLIMPIARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel7))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(jLabel5)))
                                    .addGap(9, 9, 9))))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCEDULA, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jTextFieldNOMBRE)
                            .addComponent(jTextFieldAPELLIDO_1)
                            .addComponent(jTextFieldAPELLIDO_2)
                            .addComponent(jTextFieldEDAD)
                            .addComponent(jTextFieldRESIDENCIA)
                            .addComponent(jTextFieldPUESTO)
                            .addComponent(jTextFieldCONTRASENIA))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ButtonAGREGAR)
                                    .addComponent(ButtonMODIFICAR)
                                    .addComponent(jButtonBUSCAR)
                                    .addComponent(jButtonELIMINAR)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(ButtonLIMPIAR)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldCEDULA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAPELLIDO_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAGREGAR))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAPELLIDO_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(ButtonMODIFICAR)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRESIDENCIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonBUSCAR)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButtonELIMINAR))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCONTRASENIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLIMPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCEDULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCEDULAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEDULAActionPerformed

    private void jTextFieldEDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEDADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEDADActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void ButtonAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAGREGARActionPerformed
        //AGREGAR
        Connection con = null;
        try {
            con = getConnection();
            PreparedStatement ps = con.prepareStatement("INSERT INTO empleados"
                    + "(cedula,nombre,apellido1,apellido2,edad,lugarresidencia,"
                    + "puesto,contrasena VALUES(?,?,?,?,?,?,?,?)");

            ps.setString(1, jTextFieldCEDULA.getText());
            ps.setString(2, jTextFieldNOMBRE.getText());
            ps.setString(3, jTextFieldAPELLIDO_1.getText());
            ps.setString(4, jTextFieldAPELLIDO_2.getText());
            ps.setString(5, jTextFieldEDAD.getText());
            ps.setString(6, jTextFieldRESIDENCIA.getText());
            ps.setString(7, jTextFieldPUESTO.getText());
            ps.setString(8, jTextFieldCONTRASENIA.getText());

            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "El registro fue guardado");
                limpiarTxt();

            } else {
                JOptionPane.showMessageDialog(null, "Error en registro");

            }
            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }
        //-------------------------------------------------------------
    }//GEN-LAST:event_ButtonAGREGARActionPerformed

    private void ButtonMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMODIFICARActionPerformed
        // MODIFICAR
         Connection con =null;
        try {
            con=getConnection();
            PreparedStatement ps=con.prepareStatement("UPDATE empleados SET cedula=?"
                    + ",nombre=?,apellido1,apellido2=?,edad=?,puesto=?,contrasena=? "
                    + "WHERE cedula=?");
           //donde este la cedula que le pedimos va y modifica segun lo que 
           //cambiemos
            ps.setString(8,jTextFieldCEDULA.getText());
            ps.setString(1,jTextFieldCEDULA.getText());
            ps.setString(2,jTextFieldNOMBRE.getText());
            ps.setString(3,jTextFieldAPELLIDO_1.getText());
            ps.setString(4,jTextFieldAPELLIDO_2.getText());
            ps.setString(5,jTextFieldEDAD.getText());
            ps.setString(6,jTextFieldPUESTO.getText());
            ps.setString(7,jTextFieldCONTRASENIA.getText());
           
            if (ps.executeUpdate()>0) {
                JOptionPane.showMessageDialog(null,"Registro Modificado");
                
            }else{
                JOptionPane.showMessageDialog(null,"Error en Modificar");                   
        }
                    
            
        } catch (Exception e) {
            System.err.println(e);
        }     
        
    }//GEN-LAST:event_ButtonMODIFICARActionPerformed

    private void jButtonBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBUSCARActionPerformed
        // BUSCAR
        Connection con = null;
        try {
            con = getConnection();
            PreparedStatement ps = con.prepareStatement("SELECT * FROM empleados "
                    + "WHERE cedula=?");
            ps.setString(1, jTextFieldCEDULA.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                jTextFieldCEDULA.setText(rs.getString("cedula"));
                jTextFieldNOMBRE.setText(rs.getString("nombre"));
                jTextFieldAPELLIDO_1.setText(rs.getString("apellido1"));
                jTextFieldAPELLIDO_2.setText(rs.getString("apellido2"));
                jTextFieldEDAD.setText(rs.getString("edad"));
                jTextFieldRESIDENCIA.setText(rs.getString("lugarresidencia"));
                jTextFieldPUESTO.setText(rs.getString("puesto"));
                jTextFieldCONTRASENIA.setText(rs.getString("contrasena"));
                                                            
            } else {
                //el else cuando la cedula no coincida
                JOptionPane.showMessageDialog(null, "Cedula no registrada:");
            }
            con.close();

        } catch (Exception e) {
            System.err.println(e);
        }
        
    }//GEN-LAST:event_jButtonBUSCARActionPerformed

    private void jButtonELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonELIMINARActionPerformed
        // ELIMINAR
          Connection con = null;
        try {
            con = getConnection();
            //elimina el dato con el que coincida la cedula
            PreparedStatement ps = con.prepareStatement("DELETE FROM empleados "
                    + "WHERE cedula=?");
            ps.setString(1, jTextFieldCEDULA.getText());
            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Registro Borrado");

            } else {
                JOptionPane.showMessageDialog(null, "Error en borrado");
            }
            con.close();

        } catch (Exception e) {
            System.err.println(e);
        }
        
    }//GEN-LAST:event_jButtonELIMINARActionPerformed

    private void ButtonLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLIMPIARActionPerformed
        // LIMPIAR
        limpiarTxt();
    }//GEN-LAST:event_ButtonLIMPIARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAGREGAR;
    private javax.swing.JButton ButtonLIMPIAR;
    private javax.swing.JButton ButtonMODIFICAR;
    private javax.swing.JButton jButtonBUSCAR;
    private javax.swing.JButton jButtonELIMINAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAPELLIDO_1;
    private javax.swing.JTextField jTextFieldAPELLIDO_2;
    private javax.swing.JTextField jTextFieldCEDULA;
    private javax.swing.JTextField jTextFieldCONTRASENIA;
    private javax.swing.JTextField jTextFieldEDAD;
    private javax.swing.JTextField jTextFieldNOMBRE;
    private javax.swing.JTextField jTextFieldPUESTO;
    private javax.swing.JTextField jTextFieldRESIDENCIA;
    private javax.swing.JTextField jTextField_ID;
    // End of variables declaration//GEN-END:variables
}
